namespace ShippingTrackingUtilities.USPSTrackingResult
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.18020.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class TrackResponse
    {

        private TrackResponseTrackInfo[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrackInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TrackResponseTrackInfo[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TrackResponseTrackInfo
    {

        private string classField;

        private string classOfMailCodeField;

        private string destinationCityField;

        private string destinationStateField;

        private string destinationZipField;

        private string emailEnabledField;

        private string expectedDeliveryDateField;

        private string kahalaIndicatorField;

        private string mailTypeCodeField;

        private string mPDATEField;

        private string mPSUFFIXField;

        private string originCityField;

        private string originStateField;

        private string originZipField;

        private string podEnabledField;

        private string predictedDeliveryDateField;

        private string restoreEnabledField;

        private string rramEnabledField;

        private string rreEnabledField;

        private string serviceTypeCodeField;

        private string statusField;

        private string statusCategoryField;

        private string statusSummaryField;

        private string tABLECODEField;

        private TrackResponseTrackInfoService[] serviceField;

        private TrackResponseTrackInfoTrackSummary[] trackSummaryField;

        private TrackResponseTrackInfoTrackDetail[] trackDetailField;

        private TrackResponseTrackInfoError errorField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClassOfMailCode
        {
            get
            {
                return this.classOfMailCodeField;
            }
            set
            {
                this.classOfMailCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinationCity
        {
            get
            {
                return this.destinationCityField;
            }
            set
            {
                this.destinationCityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinationState
        {
            get
            {
                return this.destinationStateField;
            }
            set
            {
                this.destinationStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DestinationZip
        {
            get
            {
                return this.destinationZipField;
            }
            set
            {
                this.destinationZipField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EmailEnabled
        {
            get
            {
                return this.emailEnabledField;
            }
            set
            {
                this.emailEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExpectedDeliveryDate
        {
            get
            {
                return this.expectedDeliveryDateField;
            }
            set
            {
                this.expectedDeliveryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KahalaIndicator
        {
            get
            {
                return this.kahalaIndicatorField;
            }
            set
            {
                this.kahalaIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MailTypeCode
        {
            get
            {
                return this.mailTypeCodeField;
            }
            set
            {
                this.mailTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MPDATE
        {
            get
            {
                return this.mPDATEField;
            }
            set
            {
                this.mPDATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MPSUFFIX
        {
            get
            {
                return this.mPSUFFIXField;
            }
            set
            {
                this.mPSUFFIXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginCity
        {
            get
            {
                return this.originCityField;
            }
            set
            {
                this.originCityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginState
        {
            get
            {
                return this.originStateField;
            }
            set
            {
                this.originStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginZip
        {
            get
            {
                return this.originZipField;
            }
            set
            {
                this.originZipField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PodEnabled
        {
            get
            {
                return this.podEnabledField;
            }
            set
            {
                this.podEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PredictedDeliveryDate
        {
            get
            {
                return this.predictedDeliveryDateField;
            }
            set
            {
                this.predictedDeliveryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RestoreEnabled
        {
            get
            {
                return this.restoreEnabledField;
            }
            set
            {
                this.restoreEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RramEnabled
        {
            get
            {
                return this.rramEnabledField;
            }
            set
            {
                this.rramEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RreEnabled
        {
            get
            {
                return this.rreEnabledField;
            }
            set
            {
                this.rreEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceTypeCode
        {
            get
            {
                return this.serviceTypeCodeField;
            }
            set
            {
                this.serviceTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StatusCategory
        {
            get
            {
                return this.statusCategoryField;
            }
            set
            {
                this.statusCategoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StatusSummary
        {
            get
            {
                return this.statusSummaryField;
            }
            set
            {
                this.statusSummaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TABLECODE
        {
            get
            {
                return this.tABLECODEField;
            }
            set
            {
                this.tABLECODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Service", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public TrackResponseTrackInfoService[] Service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrackSummary", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TrackResponseTrackInfoTrackSummary[] TrackSummary
        {
            get
            {
                return this.trackSummaryField;
            }
            set
            {
                this.trackSummaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrackDetail", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TrackResponseTrackInfoTrackDetail[] TrackDetail
        {
            get
            {
                return this.trackDetailField;
            }
            set
            {
                this.trackDetailField = value;
            }
        }

        /// <remarks/>
        public TrackResponseTrackInfoError Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TrackResponseTrackInfoService
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TrackResponseTrackInfoTrackSummary
    {

        private string eventTimeField;

        private string eventDateField;

        private string eventField;

        private string eventCityField;

        private string eventStateField;

        private string eventZIPCodeField;

        private string eventCountryField;

        private string firmNameField;

        private string nameField;

        private string authorizedAgentField;

        private string eventCodeField;

        private string deliveryAttributeCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventTime
        {
            get
            {
                return this.eventTimeField;
            }
            set
            {
                this.eventTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventDate
        {
            get
            {
                return this.eventDateField;
            }
            set
            {
                this.eventDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventCity
        {
            get
            {
                return this.eventCityField;
            }
            set
            {
                this.eventCityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventState
        {
            get
            {
                return this.eventStateField;
            }
            set
            {
                this.eventStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventZIPCode
        {
            get
            {
                return this.eventZIPCodeField;
            }
            set
            {
                this.eventZIPCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventCountry
        {
            get
            {
                return this.eventCountryField;
            }
            set
            {
                this.eventCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FirmName
        {
            get
            {
                return this.firmNameField;
            }
            set
            {
                this.firmNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AuthorizedAgent
        {
            get
            {
                return this.authorizedAgentField;
            }
            set
            {
                this.authorizedAgentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventCode
        {
            get
            {
                return this.eventCodeField;
            }
            set
            {
                this.eventCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeliveryAttributeCode
        {
            get
            {
                return this.deliveryAttributeCodeField;
            }
            set
            {
                this.deliveryAttributeCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TrackResponseTrackInfoTrackDetail
    {

        private string eventTimeField;

        private string eventDateField;

        private string eventField;

        private string eventCityField;

        private string eventStateField;

        private string eventZIPCodeField;

        private string eventCountryField;

        private string firmNameField;

        private string nameField;

        private string authorizedAgentField;

        private string eventCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventTime
        {
            get
            {
                return this.eventTimeField;
            }
            set
            {
                this.eventTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventDate
        {
            get
            {
                return this.eventDateField;
            }
            set
            {
                this.eventDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventCity
        {
            get
            {
                return this.eventCityField;
            }
            set
            {
                this.eventCityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventState
        {
            get
            {
                return this.eventStateField;
            }
            set
            {
                this.eventStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventZIPCode
        {
            get
            {
                return this.eventZIPCodeField;
            }
            set
            {
                this.eventZIPCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventCountry
        {
            get
            {
                return this.eventCountryField;
            }
            set
            {
                this.eventCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FirmName
        {
            get
            {
                return this.firmNameField;
            }
            set
            {
                this.firmNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AuthorizedAgent
        {
            get
            {
                return this.authorizedAgentField;
            }
            set
            {
                this.authorizedAgentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventCode
        {
            get
            {
                return this.eventCodeField;
            }
            set
            {
                this.eventCodeField = value;
            }
        }

        /// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TrackResponseTrackInfoError {
    
    private int numberField;
    
    private string descriptionField;
    
    private string helpFileField;
    
    private string helpContextField;
    
    /// <remarks/>
    public int Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string HelpFile {
        get {
            return this.helpFileField;
        }
        set {
            this.helpFileField = value;
        }
    }
    
    /// <remarks/>
    public string HelpContext {
        get {
            return this.helpContextField;
        }
        set {
            this.helpContextField = value;
        }
    }
}
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TrackResponseTrackInfoError
    {

        private int numberField;

        private string descriptionField;

        private string helpFileField;

        private string helpContextField;

        /// <remarks/>
        public int Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string HelpFile
        {
            get
            {
                return this.helpFileField;
            }
            set
            {
                this.helpFileField = value;
            }
        }

        /// <remarks/>
        public string HelpContext
        {
            get
            {
                return this.helpContextField;
            }
            set
            {
                this.helpContextField = value;
            }
        }
    }
}
